global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'loki'
    static_configs:
      - targets: ['66.151.41.52:3100']
  - job_name: 'node'
    static_configs:
      - targets: [ '66.151.41.52:9100' ]
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['66.151.41.52:8080']